import {
  BuildingType,
  Faction,
  GameState,
  HeroClass,
  MapTile,
  ResourceBuildingType,
  TerrainType,
  UnitType,
} from "@/lib/game/types";

export const MOCK_USER_ID = "dev-user";

export function buildMockState(): GameState {
  const tiles: MapTile[][] = Array.from({ length: 20 }, (_, y) =>
    Array.from({ length: 20 }, (_, x) => ({
      x,
      y,
      terrain: x < 12 ? TerrainType.GRASS : TerrainType.DIRT,
      elevation: 0,
      isPassable: true,
      movementCost: 1,
      // Zone 0 = west (p1), zone 1 = north-east (fully p2-owned), zone 2 =
      // south-east pocket mixing a p2 dwelling with a neutral town so the
      // minimap's neutral-town handling is exercised.
      zoneId: x < 12 ? 0 : x >= 12 && y >= 14 ? 2 : 1,
    }))
  );

  tiles[7][9].object = {
    type: "gate",
    id: "gate-dev-neutral",
    ownerId: null,
    guardianPower: 0,
  };
  tiles[15][16].object = {
    type: "adventure_building",
    id: "dwelling-dev-p2",
    subtype: "external_dwelling",
    ownerId: "p2",
    targetId: UnitType.GOG,
    amount: 8,
  };
  // Neutral town sharing zone 2 with the p2 dwelling: must stay neutral on the
  // minimap (grey marker, no enemy control tint over it).
  tiles[16][17].object = {
    type: "town",
    id: "town-dev-neutral",
    subtype: Faction.INFERNO,
    name: "Bastion Oublié",
  };

  return {
    id: "dev-game",
    status: "ACTIVE",
    maxPlayers: 2,
    turnNumber: 5,
    calendar: {
      dayNumber: 5,
      dayOfWeek: 5,
      weekNumber: 1,
      weekOfMonth: 1,
      monthNumber: 1,
      monthOfYear: 1,
      yearNumber: 1,
    },
    currentTurnPlayerId: "p1",
    // Partial budget (≈2/3 left) so the HUD turn-timer ring renders visibly,
    // while staying far from zero so it never auto-expires mid-test.
    turnTimeLimit: 600,
    currentTurnStartedAt: new Date(Date.now() - 200_000).toISOString(),
    activeCombats: [],
    actionLog: [
      {
        id: "log-dev-3",
        gameId: "dev-game",
        gamePlayerId: "p2",
        actorKind: "player",
        turnNumber: 5,
        actionType: "END_TURN",
        category: "turn",
        summary: "Adversaire termine son tour.",
        details: { action: { type: "END_TURN" } },
        createdAt: new Date("2026-05-28T10:03:00Z").toISOString(),
      },
      {
        id: "log-dev-system",
        gameId: "dev-game",
        gamePlayerId: null,
        actorKind: "system",
        turnNumber: 5,
        actionType: "TURN_READY",
        category: "turn",
        summary: "Le jour commence.",
        details: { playerId: "p1" },
        createdAt: new Date("2026-05-28T10:02:30Z").toISOString(),
      },
      {
        id: "log-dev-combat",
        gameId: "dev-game",
        gamePlayerId: "p1",
        actorKind: "player",
        turnNumber: 5,
        actionType: "START_COMBAT",
        category: "combat",
        summary: "Leon Sticky-Fingers lance un combat contre des créatures.",
        details: { combatId: "combat-dev-1", targetType: "monster", targetId: "mon-dev-1", position: { x: 6, y: 5 }, action: { type: "START_COMBAT", attackerHeroId: "h1", targetType: "monster", targetId: "mon-dev-1", mode: "MANUAL" } },
        createdAt: new Date("2026-05-28T10:02:15Z").toISOString(),
      },
      {
        id: "log-dev-resource",
        gameId: "dev-game",
        gamePlayerId: "p1",
        actorKind: "player",
        turnNumber: 5,
        actionType: "COLLECT_RESOURCE",
        category: "adventure",
        summary: "Leon Sticky-Fingers collecte des ressources.",
        details: { action: { type: "COLLECT_RESOURCE", heroId: "h1", resource: "wood", amount: 7, position: { x: 6, y: 5 } } },
        createdAt: new Date("2026-05-28T10:02:05Z").toISOString(),
      },
      {
        id: "log-dev-2",
        gameId: "dev-game",
        gamePlayerId: "p1",
        actorKind: "player",
        turnNumber: 5,
        actionType: "MOVE_HERO",
        category: "movement",
        summary: "Leon Sticky-Fingers déplace un héros.",
        details: { action: { type: "MOVE_HERO", heroId: "h1", path: [{ x: 5, y: 5 }, { x: 6, y: 5 }] } },
        createdAt: new Date("2026-05-28T10:02:00Z").toISOString(),
      },
      {
        id: "log-dev-capture",
        gameId: "dev-game",
        gamePlayerId: "p1",
        actorKind: "player",
        turnNumber: 5,
        actionType: "CAPTURE_BUILDING",
        category: "capture",
        summary: "Leon Sticky-Fingers capture une mine.",
        details: { action: { type: "CAPTURE_BUILDING", heroId: "h1", buildingId: "mine-gold-dev", path: [{ x: 6, y: 5 }, { x: 7, y: 5 }] } },
        createdAt: new Date("2026-05-28T10:01:30Z").toISOString(),
      },
      {
        id: "log-dev-1",
        gameId: "dev-game",
        gamePlayerId: "p1",
        actorKind: "player",
        turnNumber: 5,
        actionType: "BUILD",
        category: "economy",
        summary: "Leon Sticky-Fingers construit un bâtiment.",
        details: { action: { type: "BUILD", townId: "t1", building: "market" } },
        createdAt: new Date("2026-05-28T10:01:00Z").toISOString(),
      },
    ],
    gates: [
      {
        id: "gate-dev-neutral",
        position: { x: 9, y: 7 },
        ownerId: null,
        guardianPower: 0,
        garrison: [],
      },
    ],
    map: {
      width: 20,
      height: 20,
      tiles,
      zones: [
        {
          id: 0,
          templateZoneId: "dev-west",
          type: "player",
          ownerIndex: 0,
          centerX: 6,
          centerY: 10,
          baseTerrain: TerrainType.GRASS,
          value: 3000,
          hasTown: true,
        },
        {
          id: 1,
          templateZoneId: "dev-east",
          type: "player",
          ownerIndex: 1,
          centerX: 16,
          centerY: 10,
          baseTerrain: TerrainType.DIRT,
          value: 3000,
          hasTown: false,
        },
      ],
    },
    players: [
      {
        id: "p1",
        userId: MOCK_USER_ID,
        name: "Leon Sticky-Fingers",
        isAi: false,
        faction: Faction.CASTLE,
        color: "#3b82f6",
        resources: { gold: 15000, wood: 30, ore: 30, mercury: 20, crystals: 20, gems: 20, sulfur: 20 },
        heroes: [
          {
            id: "h1",
            name: "Leon",
            class: HeroClass.KNIGHT,
            level: 5,
            experience: 1200,
            stats: { attack: 4, defense: 3, spellPower: 1, knowledge: 1, morale: 0, luck: 0 },
            mana: 10,
            hasSpellBook: true,
            knownSpellIds: ["view_air"],
            artifacts: { inventory: ["centaurs_axe", "clover_fortune"], equipment: { weapon: "centaurs_axe" } },
            position: { x: 5, y: 5 },
            movement: 12,
            maxMovement: 18,
            armies: [
              { id: "a1", unitType: UnitType.PIKEMAN, count: 120, health: 1200, maxHealth: 10, position: 0 },
              { id: "a2", unitType: UnitType.ARCHER, count: 780, health: 7800, maxHealth: 10, position: 1 },
              { id: "a3", unitType: UnitType.ARCHER, count: 90, health: 900, maxHealth: 10, position: 2 },
              { id: "a4", unitType: UnitType.GRIFFIN, count: 34, health: 1020, maxHealth: 30, position: 3 },
              { id: "a5", unitType: UnitType.SWORDSMAN, count: 65, health: 2275, maxHealth: 35, position: 4 },
              { id: "a6", unitType: UnitType.MONK, count: 42, health: 1260, maxHealth: 30, position: 5 },
              { id: "a7", unitType: UnitType.CAVALIER, count: 18, health: 1800, maxHealth: 100, position: 6 },
              { id: "a8", unitType: UnitType.CENTAUR, count: 180, health: 1440, maxHealth: 8, position: 7 },
              { id: "a9", unitType: UnitType.WOOD_ELF, count: 96, health: 1440, maxHealth: 15, position: 8 },
              { id: "a10", unitType: UnitType.DWARF, count: 80, health: 1600, maxHealth: 20, position: 9 },
              { id: "a11", unitType: UnitType.GREMLIN, count: 230, health: 920, maxHealth: 4, position: 10 },
              { id: "a12", unitType: UnitType.GARGOYLE, count: 70, health: 1120, maxHealth: 16, position: 11 },
              { id: "a13", unitType: UnitType.GOLEM, count: 45, health: 1575, maxHealth: 35, position: 12 },
              { id: "a14", unitType: UnitType.IMP, count: 210, health: 840, maxHealth: 4, position: 13 },
              { id: "a15", unitType: UnitType.GOG, count: 88, health: 1144, maxHealth: 13, position: 14 },
              { id: "a16", unitType: UnitType.SKELETON, count: 320, health: 1920, maxHealth: 6, position: 15 },
              { id: "a17", unitType: UnitType.WALKING_DEAD, count: 64, health: 960, maxHealth: 15, position: 16 },
              { id: "a18", unitType: UnitType.TROGLODYTE, count: 150, health: 750, maxHealth: 5, position: 17 },
              { id: "a19", unitType: UnitType.HARPY, count: 55, health: 770, maxHealth: 14, position: 18 },
              { id: "a20", unitType: UnitType.BEHOLDER, count: 24, health: 528, maxHealth: 22, position: 19 },
            ],
          },
          {
            id: "h2",
            name: "Aldric",
            class: HeroClass.CLERIC,
            level: 2,
            experience: 200,
            stats: { attack: 1, defense: 1, spellPower: 3, knowledge: 3, morale: 0, luck: 0 },
            mana: 30,
            hasSpellBook: true,
            knownSpellIds: ["view_air"],
            artifacts: { inventory: [], equipment: {} },
            position: { x: 9, y: 7 },
            movement: 18,
            maxMovement: 18,
            armies: [],
          },
        ],
        towns: [
          {
            id: "t1",
            name: "Château Stellaire",
            faction: Faction.CASTLE,
            position: { x: 3, y: 12 },
            level: 3,
            buildings: [BuildingType.VILLAGE_HALL, BuildingType.TAVERN, BuildingType.BARRACKS, BuildingType.DWELLING_1, BuildingType.DWELLING_2],
            garrison: [],
            availableRecruits: { [UnitType.PIKEMAN]: 12, [UnitType.ARCHER]: 8 },
            lastBuiltTurn: null,
          },
        ],
        resourceBuildings: [
          { id: "rb1", type: ResourceBuildingType.GOLD_MINE, position: { x: 7, y: 3 }, ownerId: "p1", guardianPower: 0 },
          { id: "rb2", type: ResourceBuildingType.SAWMILL, position: { x: 4, y: 8 }, ownerId: "p1", guardianPower: 0 },
          { id: "rb3", type: ResourceBuildingType.ORE_PIT, position: { x: 11, y: 6 }, ownerId: "p1", guardianPower: 0 },
        ],
        isAlive: true,
        turnOrder: 0,
        exploredTiles: [],
        hasEndedTurn: false,
      },
      {
        id: "p2",
        userId: "other-user",
        name: "Adversaire",
        isAi: false,
        faction: Faction.INFERNO,
        color: "#ef4444",
        resources: { gold: 8000, wood: 10, ore: 10, mercury: 5, crystals: 5, gems: 5, sulfur: 5 },
        heroes: [],
        towns: [],
        resourceBuildings: [
          { id: "rb4", type: ResourceBuildingType.SULFUR_DUNE, position: { x: 15, y: 12 }, ownerId: "p2", guardianPower: 0 },
        ],
        isAlive: true,
        turnOrder: 1,
        exploredTiles: [],
        hasEndedTurn: false,
      },
    ],
  };
}

export const mockAuthValue = {
  data: { user: { id: MOCK_USER_ID, email: "dev@local", name: "Dev" } },
  status: "authenticated" as const,
  user: null,
};
