import type { DecorKind } from "@/lib/game/types";
import { MAP_SPRITES } from "@/lib/rendering/phaser/assets";
import type { SpriteOrigin } from "@/lib/rendering/phaser/mapObjectLayout";

export const DECOR_SPRITES: Partial<Record<DecorKind, string>> = {
  "bramble-thicket": MAP_SPRITES.decor.bramble_thicket,
  "fallen-log-barricade": MAP_SPRITES.decor.fallen_log_barricade,
  "willow-swamp-grove": MAP_SPRITES.decor.willow_swamp_grove,
  "birch-grove": MAP_SPRITES.decor.birch_grove,
  "deadwood-thicket": MAP_SPRITES.decor.deadwood_thicket,
  "flowering-hedge": MAP_SPRITES.decor.flowering_hedge,
  "grass-oak-copse": MAP_SPRITES.decor.grass_oak_copse,
  "grass-bramble-mound": MAP_SPRITES.decor.grass_bramble_mound,
  "grass-flowering-hedge": MAP_SPRITES.decor.grass_flowering_hedge,
  "grass-reed-thicket": MAP_SPRITES.decor.grass_reed_thicket,
  "grass-root-barricade": MAP_SPRITES.decor.grass_root_barricade,
  "grass-sapling-grove": MAP_SPRITES.decor.grass_sapling_grove,
  "forest-pine-grove": MAP_SPRITES.decor.forest_pine_grove,
  "forest-broadleaf-grove": MAP_SPRITES.decor.forest_broadleaf_grove,
  "forest-underwood-thicket": MAP_SPRITES.decor.forest_underwood_thicket,
  "forest-stump-ferns": MAP_SPRITES.decor.forest_stump_ferns,
  "forest-birch-pine-screen": MAP_SPRITES.decor.forest_birch_pine_screen,
  "forest-deadfall": MAP_SPRITES.decor.forest_deadfall,
  "dirt-thorn-scrub": MAP_SPRITES.decor.dirt_thorn_scrub,
  "dirt-dead-brush": MAP_SPRITES.decor.dirt_dead_brush,
  "dirt-dry-log-barrier": MAP_SPRITES.decor.dirt_dry_log_barrier,
  "dirt-root-snarl": MAP_SPRITES.decor.dirt_root_snarl,
  "dirt-cactus-brush": MAP_SPRITES.decor.dirt_cactus_brush,
  "dirt-bramble-ravine": MAP_SPRITES.decor.dirt_bramble_ravine,
  "sand-cactus-cluster": MAP_SPRITES.decor.sand_cactus_cluster,
  "sand-desert-scrub": MAP_SPRITES.decor.sand_desert_scrub,
  "sand-palm-stump": MAP_SPRITES.decor.sand_palm_stump,
  "sand-agave-barrier": MAP_SPRITES.decor.sand_agave_barrier,
  "sand-tumbleweed-heap": MAP_SPRITES.decor.sand_tumbleweed_heap,
  "sand-saltbush-clump": MAP_SPRITES.decor.sand_saltbush_clump,
  "snow-pine-grove": MAP_SPRITES.decor.snow_pine_grove,
  "snow-birch-thicket": MAP_SPRITES.decor.snow_birch_thicket,
  "snow-deadwood-barrier": MAP_SPRITES.decor.snow_deadwood_barrier,
  "snow-bramble-mound": MAP_SPRITES.decor.snow_bramble_mound,
  "snow-evergreen-drift": MAP_SPRITES.decor.snow_evergreen_drift,
  "snow-shrub-wall": MAP_SPRITES.decor.snow_shrub_wall,
  "mountain-pine-rock": MAP_SPRITES.decor.mountain_pine_rock,
  "mountain-cliff-brush": MAP_SPRITES.decor.mountain_cliff_brush,
  "mountain-deadwood": MAP_SPRITES.decor.mountain_deadwood,
  "mountain-mossy-roots": MAP_SPRITES.decor.mountain_mossy_roots,
  "mountain-fir-grove": MAP_SPRITES.decor.mountain_fir_grove,
  "mountain-rhododendron": MAP_SPRITES.decor.mountain_rhododendron,
  "swamp-willow-grove": MAP_SPRITES.decor.swamp_willow_grove,
  "swamp-mangrove-tangle": MAP_SPRITES.decor.swamp_mangrove_tangle,
  "swamp-reed-thicket": MAP_SPRITES.decor.swamp_reed_thicket,
  "swamp-cypress-cluster": MAP_SPRITES.decor.swamp_cypress_cluster,
  "swamp-bog-bramble": MAP_SPRITES.decor.swamp_bog_bramble,
  "swamp-fungus-log": MAP_SPRITES.decor.swamp_fungus_log,
  "lava-charred-thorns": MAP_SPRITES.decor.lava_charred_thorns,
  "lava-ember-roots": MAP_SPRITES.decor.lava_ember_roots,
  "lava-ash-fungus": MAP_SPRITES.decor.lava_ash_fungus,
  "lava-scorched-deadwood": MAP_SPRITES.decor.lava_scorched_deadwood,
  "lava-sulfur-shrub": MAP_SPRITES.decor.lava_sulfur_shrub,
  "lava-obsidian-bramble": MAP_SPRITES.decor.lava_obsidian_bramble,
  "underground-stalagmite-cluster": MAP_SPRITES.decor.underground_stalagmite_cluster,
  "underground-crystal-ribs": MAP_SPRITES.decor.underground_crystal_ribs,
  "underground-mushroom-thicket": MAP_SPRITES.decor.underground_mushroom_thicket,
  "underground-rubble-pillar": MAP_SPRITES.decor.underground_rubble_pillar,
  "underground-root-snarl": MAP_SPRITES.decor.underground_root_snarl,
  "massif-mountain-granite-2x2": MAP_SPRITES.decor.massif_mountain_granite_2x2,
  "massif-mountain-snowcap-2x2": MAP_SPRITES.decor.massif_mountain_snowcap_2x2,
  "massif-mountain-pine-2x2": MAP_SPRITES.decor.massif_mountain_pine_2x2,
  "massif-mountain-volcanic-2x2": MAP_SPRITES.decor.massif_mountain_volcanic_2x2,
  "massif-mountain-desert-2x2": MAP_SPRITES.decor.massif_mountain_desert_2x2,
  "massif-mountain-mossy-2x2": MAP_SPRITES.decor.massif_mountain_mossy_2x2,
  "boulder-cluster": MAP_SPRITES.decor.boulder_cluster,
};

export const BLOCKING_DECOR_ORIGINS: Partial<Record<DecorKind, SpriteOrigin>> = {
  "bramble-thicket": { originX: 0.5, originY: 0.82 },
  "fallen-log-barricade": { originX: 0.506, originY: 0.822 },
  "willow-swamp-grove": { originX: 0.512, originY: 0.84 },
  "birch-grove": { originX: 0.5, originY: 0.838 },
  "deadwood-thicket": { originX: 0.502, originY: 0.835 },
  "flowering-hedge": { originX: 0.5, originY: 0.82 },
  "boulder-cluster": { originX: 0.514, originY: 0.84 },
  "underground-stalagmite-cluster": { originX: 0.5, originY: 0.84 },
  "underground-crystal-ribs": { originX: 0.5, originY: 0.84 },
  "underground-mushroom-thicket": { originX: 0.5, originY: 0.84 },
  "underground-rubble-pillar": { originX: 0.5, originY: 0.84 },
  "underground-root-snarl": { originX: 0.5, originY: 0.84 },
  "massif-mountain-granite-2x2": { originX: 0.5, originY: 0.84 },
  "massif-mountain-snowcap-2x2": { originX: 0.5, originY: 0.84 },
  "massif-mountain-pine-2x2": { originX: 0.5, originY: 0.84 },
  "massif-mountain-volcanic-2x2": { originX: 0.5, originY: 0.84 },
  "massif-mountain-desert-2x2": { originX: 0.5, originY: 0.84 },
  "massif-mountain-mossy-2x2": { originX: 0.5, originY: 0.84 },
};

export const BLOCKING_DECOR_SPRITE_SIZE = 72;
export const BLOCKING_DECOR_GROUND_OFFSET = 16;

export const BLOCKING_DECOR_SPRITE_METRICS: Partial<Record<DecorKind, { size: number; groundOffset: number }>> = {
  "boulder-cluster": {
    size: 58,
    groundOffset: 8,
  },
  "fallen-log-barricade": {
    size: 64,
    groundOffset: 7,
  },
  "bramble-thicket": {
    size: 68,
    groundOffset: 8,
  },
  "underground-stalagmite-cluster": {
    size: 54,
    groundOffset: 6,
  },
  "underground-crystal-ribs": {
    size: 56,
    groundOffset: 6,
  },
  "underground-mushroom-thicket": {
    size: 54,
    groundOffset: 6,
  },
  "underground-rubble-pillar": {
    size: 56,
    groundOffset: 6,
  },
  "underground-root-snarl": {
    size: 54,
    groundOffset: 6,
  },
  "massif-mountain-granite-2x2": {
    size: 158,
    groundOffset: 18,
  },
  "massif-mountain-snowcap-2x2": {
    size: 158,
    groundOffset: 18,
  },
  "massif-mountain-pine-2x2": {
    size: 158,
    groundOffset: 18,
  },
  "massif-mountain-volcanic-2x2": {
    size: 158,
    groundOffset: 18,
  },
  "massif-mountain-desert-2x2": {
    size: 158,
    groundOffset: 18,
  },
  "massif-mountain-mossy-2x2": {
    size: 158,
    groundOffset: 18,
  },
};
