-- Durable, privacy-safe lifecycle metrics for anonymous accounts.
create table if not exists public.anonymous_account_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event_type text not null check (event_type in ('guest_created', 'conversion_requested', 'conversion_completed')),
  occurred_at timestamptz not null default now(),
  unique (user_id, event_type)
);

create index if not exists anonymous_account_events_occurred_at_idx
  on public.anonymous_account_events (occurred_at);
create index if not exists anonymous_account_events_type_occurred_at_idx
  on public.anonymous_account_events (event_type, occurred_at);

alter table public.anonymous_account_events enable row level security;

insert into public.app_settings (key, value)
values ('anonymous_account_tracking_started_at', to_jsonb(now()))
on conflict (key) do nothing;

-- Past conversions cannot be reconstructed. Seed only guests that still exist.
insert into public.anonymous_account_events (user_id, event_type, occurred_at)
select id, 'guest_created', created_at
from public.profiles
where is_guest = true
on conflict (user_id, event_type) do nothing;
